
import { createClient } from '@supabase/supabase-js';
import { MOCK_CATEGORIES, MOCK_SUBCATEGORIES, MOCK_PRODUCTS } from '../../services/mockFallback';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

const isValidUrl = (url) => {
    try { new URL(url); return true; } catch { return false; }
};

export const isSupabaseConfigured = !!(
    supabaseUrl &&
    supabaseAnonKey &&
    !supabaseUrl.includes('YOUR_SUPABASE_URL') &&
    !supabaseUrl.includes('DISABLED') &&
    isValidUrl(supabaseUrl) &&
    supabaseUrl.includes('.supabase.co')
);

if (!isSupabaseConfigured) {
    console.warn('[mockDb] Supabase not configured or disabled — running in demo/fallback mode.');
}

// Use a dummy URL when disabled so createClient doesn't throw
export const supabase = createClient(
    isSupabaseConfigured ? supabaseUrl : 'https://placeholder.supabase.co',
    isSupabaseConfigured ? supabaseAnonKey : 'placeholder-key'
);

// Helper to map Supabase product result to frontend structure
const mapProduct = (p) => {
    let features = [];
    try {
        features = p.features ? JSON.parse(p.features) : [];
    } catch (e) {
        // Fallback if it's just a string
        features = p.features ? [p.features] : [];
    }

    // Derive category from the subcategory join (products table has no direct category_id)
    // Handle both object and array formats just in case, and fallback to direct category_id if it exists.
    let categoryId = p.category_id || p.category;
    if (p.sub_categories) {
        if (Array.isArray(p.sub_categories)) {
            categoryId = p.sub_categories[0]?.category_id || categoryId;
        } else {
            categoryId = p.sub_categories.category_id || categoryId;
        }
    }

    return {
        ...p,
        id: p.id,
        category: categoryId, // Mapped for frontend
        subcategory: p.sub_category_id, // Mapped for frontend
        features: Array.isArray(features) ? features : [features],
        images: p.product_images ? p.product_images.map(img => img.image_url) : [],
        is_featured: p.is_featured, // Pass through
        sub_category_id: undefined, // Cleanup
        product_images: undefined,   // Cleanup
        sub_categories: undefined    // Cleanup
    };
};

class SupabaseDatabase {
    constructor() {
        console.log('Supabase Database Service Initialized (Schema V2)');
    }

    // --- Categories ---
    async getCategories() {
        try {
            const { data, error } = await supabase
                .from('categories')
                .select('*')
                .order('name');

            if (error) throw error;
            return data || [];
        } catch (err) {
            console.error('Offline mode: Using fallback categories');
            return [...MOCK_CATEGORIES];
        }
    }

    async createCategory(catData) {
        // ID is UUID generated by DB
        const payload = { name: catData.name };
        if (catData.image_url) payload.image_url = catData.image_url;

        const { data, error } = await supabase
            .from('categories')
            .insert([payload]) // Ignore provided ID, let DB generate
            .select()
            .single();

        if (error) throw error;
        return data;
    }

    async deleteCategory(id) {
        const { error } = await supabase
            .from('categories')
            .delete()
            .eq('id', id);

        if (error) throw error;
        return true;
    }

    // --- Subcategories ---
    async getSubcategories(categoryId = null) {
        try {
            let query = supabase.from('sub_categories').select('*').order('name');

            if (categoryId) {
                query = query.eq('category_id', categoryId);
            }

            const { data, error } = await query;
            if (error) throw error;
            return data;
        } catch(err) {
            console.error('Offline Mode: Using fallback subcategories');
            if (categoryId) return MOCK_SUBCATEGORIES.filter(s => s.category_id === categoryId);
            return [...MOCK_SUBCATEGORIES];
        }
    }

    async createSubcategory(subData) {
        // Ensure category_id is present
        const payload = {
            name: subData.name,
            category_id: subData.category_id || subData.category // Handle both prop names
        };
        if (subData.image_url) payload.image_url = subData.image_url;

        const { data, error } = await supabase
            .from('sub_categories')
            .insert([payload])
            .select()
            .single();

        if (error) throw error;
        return data;
    }

    async deleteSubcategory(id) {
        const { error } = await supabase
            .from('sub_categories')
            .delete()
            .eq('id', id);

        if (error) throw error;
        return true;
    }

    // --- Products ---
    async getProducts(page = 1, limit = 20, search = '', filters = {}) {
        try {
            const from = (page - 1) * limit;
            const to = from + limit - 1;

            let query = supabase
                .from('products')
                .select('*, product_images(image_url), sub_categories(category_id)', { count: 'exact' });

            if (search) {
                query = query.or(`name.ilike.%${search}%,description.ilike.%${search}%`);
            }

            if (filters.category) {
                query = supabase
                    .from('products')
                    .select('*, product_images(image_url), sub_categories!inner(category_id)', { count: 'exact' })
                    .eq('sub_categories.category_id', filters.category);
            }

            if (filters.subcategory) {
                query = query.eq('sub_category_id', filters.subcategory);
            }

            const { data, error, count } = await query
                .range(from, to)
                .order('created_at', { ascending: false });

            if (error) throw error;

            return {
                data: data.map(mapProduct),
                total: count || 0,
                page,
                limit
            };
        } catch(err) {
            console.error('Offline Mode: Using fallback products');
            let filtered = [...MOCK_PRODUCTS];
            if (search) {
                const s = search.toLowerCase();
                filtered = filtered.filter(p => p.name.toLowerCase().includes(s) || p.description.toLowerCase().includes(s));
            }
            if (filters.category) {
                filtered = filtered.filter(p => p.category === filters.category);
            }
            if (filters.subcategory) {
                filtered = filtered.filter(p => p.subcategory === filters.subcategory);
            }
            const from = (page - 1) * limit;
            const paged = filtered.slice(from, from + limit);
            
            return {
                data: paged,
                total: filtered.length,
                page,
                limit
            };
        }
    }

    async getProduct(id) {
        const { data, error } = await supabase
            .from('products')
            .select('*, product_images(image_url), sub_categories(category_id)')
            .eq('id', id)
            .single();

        if (error) {
            console.error('Error fetching product:', error);
            return null;
        }

        return mapProduct(data);
    }

    async createProduct(prodData) {
        console.log('[createProduct] Incoming prodData before destructuring:', JSON.stringify(prodData, null, 2));
        const { images, category, subcategory, features, ...rest } = prodData;
        console.log('[createProduct] Extracted images array:', images);

        const productPayload = {
            ...rest,
            sub_category_id: subcategory || null, // Empty string -> null for UUID column
            features: JSON.stringify(features || []), // Store as JSON string in text column
            is_featured: rest.is_featured || false
        };

        // Cleaning up undefineds
        delete productPayload.id; // Allow DB to generate UUID

        const { data: product, error: prodError } = await supabase
            .from('products')
            .insert([productPayload])
            .select()
            .single();

        if (prodError) throw prodError;

        if (images && images.length > 0) {
            const imageInserts = images.map(img => {
                // Handle both objects (new uploads) and strings (existing urls during edits/sync)
                if (typeof img === 'object' && img !== null) {
                    return {
                        product_id: product.id,
                        image_url: img.secure_url,
                        public_id: img.public_id
                    };
                } else {
                    return {
                        product_id: product.id,
                        image_url: img,
                        public_id: null // Fallback if no public ID exists for legacy data
                    };
                }
            });

            console.log('[createProduct] Preparing to insert into product_images table:', JSON.stringify(imageInserts, null, 2));

            const { error: imgError } = await supabase
                .from('product_images')
                .insert(imageInserts);

            if (imgError) console.error('Error saving images:', imgError);
        }

        return this.getProduct(product.id);
    }

    async updateProduct(id, prodData) {
        const { images, category, subcategory, features, ...rest } = prodData;

        const updates = {
            ...rest,
            sub_category_id: subcategory || null, // Empty string -> null for UUID column
            features: JSON.stringify(features || [])
        };
        // Remove helper fields
        delete updates.created_at;
        delete updates.product_images;
        delete updates.sub_categories;

        const { error: prodError } = await supabase
            .from('products')
            .update(updates)
            .eq('id', id);

        if (prodError) throw prodError;

        if (images) {
            await supabase.from('product_images').delete().eq('product_id', id);

            if (images.length > 0) {
                const imageInserts = images.map(url => ({
                    product_id: id,
                    image_url: url
                }));
                await supabase.from('product_images').insert(imageInserts);
            }
        }

        return this.getProduct(id);
    }

    async deleteProduct(id) {
        // Delete images first (if no cascade)
        await supabase.from('product_images').delete().eq('product_id', id);

        const { error } = await supabase
            .from('products')
            .delete()
            .eq('id', id);

        if (error) throw error;
        return true;
    }

    // --- Storage (via Cloudinary backend) ---
    async uploadImage(file, onProgress) {
        const UPLOAD_URL = 'http://localhost:5000/upload';

        const formData = new FormData();
        formData.append('image', file);

        return new Promise((resolve, reject) => {
            const xhr = new XMLHttpRequest();
            xhr.open('POST', UPLOAD_URL);

            // Listen for upload progress
            if (onProgress && xhr.upload) {
                xhr.upload.onprogress = (event) => {
                    if (event.lengthComputable) {
                        const percentComplete = Math.round((event.loaded / event.total) * 100);
                        onProgress(percentComplete);
                    }
                };
            }

            xhr.onload = () => {
                if (xhr.status >= 200 && xhr.status < 300) {
                    try {
                        const res = JSON.parse(xhr.responseText);
                        resolve({
                            secure_url: res.secure_url,
                            public_id: res.public_id
                        });
                    } catch (e) {
                        reject(new Error('Invalid JSON response'));
                    }
                } else {
                    try {
                        const err = JSON.parse(xhr.responseText);
                        reject(new Error(`Upload failed: ${err.error || 'Unknown error'}`));
                    } catch (e) {
                        reject(new Error(`Upload failed with status: ${xhr.status}`));
                    }
                }
            };

            xhr.onerror = () => {
                reject(new Error('Cannot reach upload server. Make sure the backend is running:\n  cd server && npm run dev'));
            };

            xhr.send(formData);
        });
    }
}

export const db = new SupabaseDatabase();
